apiVersion: pipeline.tekton.dev/v1beta1
kind: Condition
metadata:
  name: match-only-paths
  namespace: tekton-ci
spec:
  params:
    - name: paths
      description: Regular expression to match files changed
      type: array
  resources:
    - name: source
      type: git
  check:
    image: alpine/git
    script: |
      #!/bin/sh
      set -ex
      set -o pipefail
      BACK="HEAD~$(( $(params.gitCloneDepth) - 1 ))"
      cd $(resources.source.path)
      git diff-tree --no-commit-id --name-only -r HEAD $BACK | \
          grep -E '$(params.regex)'
