apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-ci
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-ci
rules:
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-ci
subjects:
- kind: ServiceAccount
  name: tekton-ci
roleRef:
  kind: Role
  name: tekton-ci
  apiGroup: rbac.authorization.k8s.io
