kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-ci-http
rules:
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-ci-http
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: tekton-ci-http
  apiGroup: rbac.authorization.k8s.io
